# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3c480883b362aef5951c8796aa3262aee6d6ab8d864484d231ff7ef3028c4ed33e69fc4913c8a1436d523663833fed23cd56d4e81e9ce3d0e3daf946f66b9d6

test:
  secret_key_base: a78aae0c3aa93cbbc40cd8bda6199b3c7870acf584a1fadbaff9f6704874c08005adf42456be62c0493cc8434b3fa095275d0bc01c8f9bd885b80e374f87478c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
